# New analysis with the new dataset



```{r}

library(tidyverse)
library(kableExtra)
load("C:\\Users\\Adelson\\Desktop\\pendrive\\bancos_workspace\\unidos.RData")

plyr::revalue(unidos$MFCcat, c('FP' = 'Family Physician')) -> unidos$MFCcat
names(unidos)[names(unidos) == 'MFCcat'] <- 'Category'

glimpse(unidos)

```



# New 

```{r}

unidos_novo <- unidos %>% filter(match != "so_velho")

tabela <- unidos_novo %>% 
  group_by(Category) %>% 
  summarise(Absolute = n()) %>% 
  slice(1:4L) %>%
  mutate(Proportion = round(Absolute/sum(Absolute)*100,1))


kableExtra::kable(tabela) %>% kable_styling(bootstrap_options = c("striped", "hover"))
```

# Only medical consultation

```{r}
medix <- tabela %>% slice(1:2L) %>% 
  mutate(Proportion = round(Absolute/sum(Absolute)*100,1))

kableExtra::kable(medix) %>% kable_styling(bootstrap_options = c("striped", "hover"))
```




```{r}

consultas <- unidos

## categorizando as morbidades

HAS <- c('I10','I11', 'I12', 'I13', 'I14', 'I15')
HAScomplicada <- c('I11', 'I12', 'I13', 'I14', 'I15')
dislipidemia <- c('E78')
obesidade <- c('E66')
anemias <- c('D50','D51', 'D52','D53')
alcool <- c('F10', 'E52', 'G621', 'I426', 'K292', 'K700', 'K703', 'K709', 'T51', 'Z502', 'Z714', 'Z721')
drogas <- c('F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F18', 'F19', 'Z715', 'Z722')
psicoses <- c('F20', 'F22', 'F23', 'F24','F25', 'F28', 'F29', 'F302', 'F312', 'F315')
depre <- c('F204', 'F313', 'F314', 'F315', 'F32', 'F33', 'F341', 'F412', 'F432')
hipoT <- c('E00', 'E01', 'E02', 'E03', 'E890')
arritmia <- c('I441', 'I442', 'I443', 'I456', 'I459', 'I47', 'I48', 'I49', 'R000', 'R001', 'R008', 'T821', 'Z450', 'Z950')
coagulo <- c('D65', 'D66', 'D67', 'D68', 'D691', 'D693', 'D694', 'D695', 'D696')
reumato <- c('L940', 'L941', 'L943', 'M05', 'M06', 'M08', 'M120', 'M123', 'M30', 'M310', 
             'M313', 'M32', 'M33', 'M34', 'M35', 'M45', 'M461', 'M468', 'M469')
valvular <- c('A520', 'I05', 'I06', 'I07', 'I08', 'I091', 'I098', 'I34', 'I35', 'I36', 'I37', 
              'I38', 'I39', 'Q230', 'Q231', 'Q232','Q233', 'Z952', 'Z953', 'Z954')
circ_pulm <- c('I26', 'I27', 'I280', 'I288', 'I289')
neuro <- c('G10', 'G11', 'G12','G13', 'G20', 'G21', 'G22', 'G254', 'G255', 'G312', 'G318', 
           'G319', 'G32', 'G35', 'G36', 'G37', 'G40', 'G41', 'G931', 'G934', 'R470', 'R56')
CI <- c("I21", "I22", "I252")
ICC <- c('I099', 'I110', 'I130', 'I132', 'I255', 'I420', 'I425', 'I426', 'I427', 'I428', 'I429', 'I43', 'I50', 'P290')
vascular_periferica <- c('I70', 'I71', 'I731', 'I738', 'I739', 'I771', 'I790', 'I792', 'K551', 'K558', 'K559', 'Z958', 'Z959')
stroke <- c('G45', 'G46', 'H340', 'I6')
dementia <- c('F00', 'F01', 'F02', 'F03', 'F051', 'G30', 'G310', 'G311')
COPD <- c('I278', 'I279', 'J4', 'J60', 'J61', 'J62', 'J63', 'J64', 'J65', 'J66', 'J67', 'J684', 'J701', 'J703')
peptic <- c('K25', 'K26', 'K27', 'K28')
DMOK <- c('E100', 'E101', 'E106', 'E108', 'E109', 'E110', 'E111', 'E116', 'E118', 'E119', 'E120', 'E121', 'E126', 'E128', 'E129', 'E130', 'E131', 'E136', 'E138', 'E139', 'E140', 'E141', 'E146', 'E148', 'E149')
DMcomplica <- c('E102', 'E103', 'E104', 'E105', 'E107', 'E112', 'E113', 'E114', 'E115', 'E117', 'E122', 'E123', 'E124', 'E125', 'E127', 'E132', 'E133', 'E134', 'E135', 'E137', 'E142', 'E143', 'E144', 'E145', 'E147')
plegia <- c('G041', 'G114', 'G801', 'G802', 'G81', 'G82', 'G830', 'G831', 'G832', 'G833', 'G834', 'G839')
IRC <- c('I120', 'I131', 'N032', 'N033', 'N034', 'N035', 'N036', 'N037', 'N052', 'N053', 'N054', 'N055', 'N056', 'N057', 'N18', 'N19', 'N250', 'Z490', 'Z491', 'Z492', 'Z940', 'Z992')
neoplasia <- c('C0', 'C1', 'C20','C21','C22','C23','C24','C25','C26', 'C30', 'C31', 'C32', 'C33', 'C34', 'C37', 'C38', 'C39', 'C40', 'C41', 'C43', 'C45', 'C46', 'C47', 'C48', 'C49', 'C50', 'C51', 'C52', 'C53', 'C54', 'C55', 'C56', 'C57', 'C58', 'C6', 'C70', 'C71', 'C72', 'C73', 'C74', 'C75', 'C76', 'C81', 'C82', 'C83', 'C84', 'C85', 'C88', 'C90', 'C91', 'C92', 'C93', 'C94', 'C95', 'C96', 'C97','C77', 'C78', 'C79', 'C80')
liver <- c('B18', 'K700', 'K701', 'K702', 'K703', 'K709', 'K713', 'K715', 'K717', 'K73', 'K74', 'K760', 'K762', 'K763', 'K764', 'K768', 'K769', 'Z944','I85', 'I859', 'I864', 'I982', 'K704', 'K711', 'K721', 'K729', 'K765', 'K766', 'K767')
SIDA <- c('B20', 'B21', 'B22', 'B24')

imunizaveis_csap <- c('A33','A34','A35','A36','A37','A95','B16','B05','B06',
                 'B26','G000', 'A170', 'A19')
evitaveis_csap <- c('A15','A16','A18','A171','A172','A173','A174','A175','A176','A177',
               'A178','A179','I00','I01','I02','A51','A52','A53','B50','B51','B52',
               'B53','B54','B77')
gastroenterites_csap <- c('E86','A00','A01','A02','A03','A04','A05','A06',
                     'A07','A08','A09')
anemia_csap <- c('D50')
nutricionais_csap <- c('E40','E41','E42','E43','E44','E45','E46',
                  'E5','E60','E61','E62','E63','E64')
orl_csap <- c('H66','J00','J01','J02','J03','J06','J31')
pneumonias_csap <- c('J13','J14','J153','J154','J158','J159','J181')
asma_csap <- c('J45','J46')
pulmonares_csap <- c('J20','J21','J40','J41','J42','J43','J44','J47')
HAS_csap <- c('I10','I11')
angina_csap <- c('I20')
ICC_csap <- c('I50','J81')
AVC_csap <- c('I63','I64','I65','I66','I67','I69','G45','G46')
DM_csap <- c('E10','E11','E12','E13','E14')
epilepsia_csap <- c('G40','G41')
ITU_csap <- c('N10','N11','N12','N30','N34','N390')
piodermite_csap <- c('A46','L01','L02','L03','L04','L08')
DIP_csap <- c('N70','N71','N72','N73','N75','N76')
peptica_csap <- c('K25','K26','K27','K28','K920','K921','K922')
parto_csap <- c('O23','A50','P350')
diu <- c('Z301')


consultas$DATA_NUM <- as.numeric(consultas$mes) # first day of the month into a number.


## Chronic morbidities

consultas$HAS <- as.numeric(ifelse(grepl(paste(HAS, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$HAScomplicada <- as.numeric(ifelse(grepl(paste(HAScomplicada, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$DMOK <- as.numeric(ifelse(grepl(paste(DMOK, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$DMcomplica <- as.numeric(ifelse(grepl(paste(DMcomplica, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$obesidade <- as.numeric(ifelse(grepl(paste(obesidade, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$dislipidemia <- as.numeric(ifelse(grepl(paste(dislipidemia, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$anemias <- as.numeric(ifelse(grepl(paste(anemias, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$alcool <- as.numeric(ifelse(grepl(paste(alcool, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$drogas <- as.numeric(ifelse(grepl(paste(drogas, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$psicoses <- as.numeric(ifelse(grepl(paste(psicoses, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$depre <- as.numeric(ifelse(grepl(paste(depre, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$hipoT <- as.numeric(ifelse(grepl(paste(hipoT, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$arritmia <- as.numeric(ifelse(grepl(paste(arritmia, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$coagulo <- as.numeric(ifelse(grepl(paste(coagulo, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$reumato <- as.numeric(ifelse(grepl(paste(reumato, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$valvular <- as.numeric(ifelse(grepl(paste(valvular, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$circ_pulm <- as.numeric(ifelse(grepl(paste(circ_pulm, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$neuro <- as.numeric(ifelse(grepl(paste(neuro, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$stroke <- as.numeric(ifelse(grepl(paste(stroke, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$dementia <- as.numeric(ifelse(grepl(paste(dementia, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$CI <- as.numeric(ifelse(grepl(paste(CI, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$ICC <- as.numeric(ifelse(grepl(paste(ICC, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$vascular_periferica <- as.numeric(ifelse(grepl(paste(vascular_periferica, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$COPD <- as.numeric(ifelse(grepl(paste(COPD, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$peptic <- as.numeric(ifelse(grepl(paste(peptic, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$plegia <- as.numeric(ifelse(grepl(paste(plegia, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$IRC <- as.numeric(ifelse(grepl(paste(IRC, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$liver <- as.numeric(ifelse(grepl(paste(liver, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$SIDA <- as.numeric(ifelse(grepl(paste(SIDA, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))

## CSAPs

consultas$imunizaveis_csap <- as.numeric(ifelse(grepl(paste(imunizaveis_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$evitaveis_csap <- as.numeric(ifelse(grepl(paste(evitaveis_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$gastroenterites_csap <- as.numeric(ifelse(grepl(paste(gastroenterites_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$anemia_csap <- as.numeric(ifelse(grepl(paste(anemia_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$nutricionais_csap <- as.numeric(ifelse(grepl(paste(nutricionais_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$orl_csap <- as.numeric(ifelse(grepl(paste(orl_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$pneumonias_csap <- as.numeric(ifelse(grepl(paste(pneumonias_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$asma_csap <- as.numeric(ifelse(grepl(paste(asma_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$pulmonares_csap <- as.numeric(ifelse(grepl(paste(pulmonares_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$HAS_csap <- as.numeric(ifelse(grepl(paste(HAS_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$angina_csap <- as.numeric(ifelse(grepl(paste(angina_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$ICC_csap <- as.numeric(ifelse(grepl(paste(ICC_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$AVC_csap <- as.numeric(ifelse(grepl(paste(AVC_csap, collapse = "|"),  consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$DM_csap <- as.numeric(ifelse(grepl(paste(DM_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$epilepsia_csap <- as.numeric(ifelse(grepl(paste(epilepsia_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$ITU_csap <- as.numeric(ifelse(grepl(paste(ITU_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$piodermite_csap <- as.numeric(ifelse(grepl(paste(piodermite_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$DIP_csap <- as.numeric(ifelse(grepl(paste(DIP_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$peptica_csap <- as.numeric(ifelse(grepl(paste(peptica_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$parto_csap <- as.numeric(ifelse(grepl(paste(parto_csap, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))
consultas$diu <- as.numeric(ifelse(grepl(paste(diu, collapse = "|"), consultas$cid10) == TRUE, consultas$DATA_NUM, NA))


# HEMOGRAM
hemograma <- c('202020380') 
consultas$hemograma <- as.integer(ifelse(grepl(paste(hemograma, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# CREATININE
creatinina <- c('202010317')
consultas$creatinina <- as.integer(ifelse(grepl(paste(creatinina, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# HDL CHOLESTEROL
HDL <- c('202010279') 
consultas$HDL <- as.integer(ifelse(grepl(paste(HDL, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# LDL CHOLESTEROL
LDL <- c('202010287') 
consultas$LDL <- as.integer(ifelse(grepl(paste(LDL, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# TOTAL CHOLESTEROL
CT <- c('202010295') 
consultas$CT <- as.integer(ifelse(grepl(paste(CT, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# TRIGLYCERID
TG <- c('202010678') 
consultas$TG <- as.integer(ifelse(grepl(paste(TG, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# UREA
ureia <- c('202010694') 
consultas$ureia <- as.integer(ifelse(grepl(paste(ureia, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# UIC ACID
urico <- c('202010120') 
consultas$urico <- as.integer(ifelse(grepl(paste(urico, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# TSH
TSH <- c('202060250') 
consultas$TSH <- as.integer(ifelse(grepl(paste(TSH, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# T3
T3 <- c('202060390') 
consultas$T3 <- as.integer(ifelse(grepl(paste(T3, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# T4
T4 <- c('202060373') 
consultas$T4 <- as.integer(ifelse(grepl(paste(T4, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# FREE T4
T4L <- c('202060381') 
consultas$T4L <- as.integer(ifelse(grepl(paste(T4L, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# SODIUM
sodio <- c('202010635') 
consultas$sodio <- as.integer(ifelse(grepl(paste(sodio, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# PSA
PSA <- c('202030105') 
consultas$PSA <- as.integer(ifelse(grepl(paste(PSA, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

#GLUCOSE
glicose <- c('202010473') 
consultas$glicose <- as.integer(ifelse(grepl(paste(glicose, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# HEMOGLOBIN A1C
A1C <- c('202010503') 
consultas$A1C <- as.integer(ifelse(grepl(paste(A1C, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# URINE SEDIMENT
pu <- c('202050017') 
consultas$pu <- as.integer(ifelse(grepl(paste(pu, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# BILIRRUBINE
bili <- c('202010201')
consultas$bili <- as.integer(ifelse(grepl(paste(bili, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# CALCIUM
calcio <- c('202010210')
consultas$calcio <- as.integer(ifelse(grepl(paste(calcio, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# GAMA GT
gamagt <- c('202010465')
consultas$gamagt <- as.integer(ifelse(grepl(paste(gamagt, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# FSH
fsh <- c('202060233')
consultas$fsh <- as.integer(ifelse(grepl(paste(fsh, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# LH
lh <- c('202060241')
consultas$lh <- as.integer(ifelse(grepl(paste(lh, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# AST/TGO
tgo <- c('202010643')
consultas$tgo <- as.integer(ifelse(grepl(paste(tgo, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# ALT/TGP
tgp <- c('202010651')
consultas$tgp <- as.integer(ifelse(grepl(paste(tgp, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# ESR
vhs <- c('202020150')
consultas$vhs <- as.integer(ifelse(grepl(paste(vhs, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# TOXOPLASMOSIS IgG
toxoigg <- c('202030768')
consultas$toxoigg <- as.integer(ifelse(grepl(paste(toxoigg, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# TOXOPLASMOSIS IgM
toxoigm <- c('202030873')
consultas$toxoigm <- as.integer(ifelse(grepl(paste(toxoigm, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# MEASLES IgG
rubeolaigg <- c('202030814')
consultas$rubeolaigg <- as.integer(ifelse(grepl(paste(rubeolaigg, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# MEASLES IgM
rubeolaigm <- c('202030920')
consultas$rubeolaigm <- as.integer(ifelse(grepl(paste(rubeolaigm, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# ALKALINE FOSFATASE
fa <- c('202010422')
consultas$fa <- as.integer(ifelse(grepl(paste(fa, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))

# EGGS
epf <- c('202040127')
consultas$epf <- as.integer(ifelse(grepl(paste(epf, collapse = "|"), consultas$PROCEDIMENTO_SOLICITADO), consultas$DATA_NUM, NA))




consultas$hemograma_valor <- consultas$hemograma*4.11

consultas$creatinina_valor <- consultas$creatinina*1.85

consultas$HDL_valor <- consultas$HDL*3.51

consultas$LDL_valor <- consultas$LDL*3.51

consultas$CT_valor <- consultas$CT*1.85

consultas$TG_valor <- consultas$TG*3.51

consultas$ureia_valor <- consultas$ureia*1.85

consultas$urico_valor <- consultas$urico*1.85

consultas$TSH_valor <- consultas$TSH*8.96

consultas$T3_valor <- consultas$T3*12.54

consultas$T4_valor <- consultas$T4*8.76

consultas$T4L_valor <- consultas$T4L*11.6

consultas$sodio_valor <- consultas$sodio*1.85

consultas$PSA_valor <- consultas$PSA*16.42

consultas$glicose_valor <- consultas$glicose*1.85

consultas$A1C_valor <- consultas$A1C*7.86

consultas$pu_valor <- consultas$pu*3.70

consultas$bili_valor <- consultas$bili*2.01

consultas$calcio_valor <- consultas$calcio*1.85

consultas$gamagt_valor <- consultas$gamagt*3.51

consultas$fsh_valor <- consultas$fsh*7.89

consultas$lh_valor <- consultas$lh*8.97

consultas$tgo_valor <- consultas$tgo*2.01

consultas$tgp_valor <- consultas$tgp*2.01

consultas$vhs_valor <- consultas$vhs*2.73

consultas$toxoigg_valor <- consultas$toxoigg*16.97

consultas$toxoigm_valor <- consultas$toxoigm*18.55

consultas$rubeolaigg_valor <- consultas$rubeolaigg*17.16

consultas$rubeolaigm_valor <- consultas$rubeolaigm*17.16

consultas$fa_valor <- consultas$fa*2.01

consultas$epf_valor <- consultas$epf*1.65



tric <- c('TRIPTILINA')
consultas$triciclico <- as.integer(ifelse(grepl(paste(tric, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


omeprazol <- c('OMEPRAZOL')
consultas$omeprazol <- as.integer(ifelse(grepl(paste(omeprazol, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


diazepam <- c('AZEPAM', "AZEPAN")
consultas$diazepam <- as.integer(ifelse(grepl(paste(diazepam, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


estatina <- c('STATINA')
consultas$estatina <- as.integer(ifelse(grepl(paste(estatina, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


amox <- c('AMOXIC')
consultas$amox <- as.integer(ifelse(grepl(paste(amox, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


aas <- c('ACIDO ACETILSALICILICO 100MG')
consultas$aas <- as.integer(ifelse(grepl(paste(aas, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


pen <- c('PENICILINA')
consultas$pen <- as.integer(ifelse(grepl(paste(pen, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


azi <- c('AZITROMICINA')
consultas$azi <- as.integer(ifelse(grepl(paste(azi, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


cef <- c('CEFALEXINA')
consultas$cef <- as.integer(ifelse(grepl(paste(cef, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))


quino <- c('FLOXACIN')
consultas$quino <- as.integer(ifelse(grepl(paste(quino, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))

# METFORMINA
metformina <- c('METFORMINA')
consultas$metformina <- as.integer(ifelse(grepl(paste(metformina, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))

# FLUOXETINA
fluoxetina <- c('XETINA')
consultas$fluoxetina <- as.integer(ifelse(grepl(paste(fluoxetina, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))

# DICLOFENACO
diclofenaco <- c('DICLOFENACO')
consultas$diclofenaco <- as.integer(ifelse(grepl(paste(diclofenaco, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))

# IBUPROFENO
ibuprofeno <- c('IBUPROFENO')
consultas$ibuprofeno <- as.integer(ifelse(grepl(paste(ibuprofeno, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))

# FLUCONAZOL 150 MG
fluconazol <- c('FLUCONAZOL 150 MG')
consultas$fluconazol <- as.integer(ifelse(grepl(paste(fluconazol, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))

# DIPIRONA
dipirona <- c('DIPIRONA')
consultas$dipirona <- as.integer(ifelse(grepl(paste(dipirona, collapse = "|"), consultas$medicamento), consultas$DATA_NUM, NA))

save(consultas, file = "C:\\Users\\Adelson\\Desktop\\pendrive\\bancos_workspace\\consultas_novo.RData")

```

# Database "novo"


```{r}


cadastrados <- read.csv("C:\\Users\\Adelson\\Desktop\\pendrive\\bancos_workspace\\prime_cadastros_19072019.csv", 
                       header = TRUE, sep = ";", dec = ",")
 
cadastrados$DATA_NASC <- as.Date(cadastrados$DATA_NASC, format = "%d/%m/%Y")
cadastrados$DATA_INSCRICAO <- as.Date(cadastrados$DATA_INSCRICAO, format = "%d/%m/%Y")
cadastrados$DATA_PRIMEIRO_ATEND <- as.Date(cadastrados$DT_PRIMEIRO_ATEND, format = "%d/%m/%Y")
cadastrados$DATA_ULTIMO_ATEND <- as.Date(cadastrados$DT_ULTIMO_ATEND, format = "%d/%m/%Y")
cadastrados$DATA_PRIMEIRA_VISITA <- as.Date(cadastrados$DT_PRIMEIRA_VISITA, format = "%d/%m/%Y")
cadastrados$DATA_ULTIMA_VISITA <- as.Date(cadastrados$DT_ULTIMA_VISITA, format = "%d/%m/%Y")
cadastrados$DATA_PRIMEIRA_DISPENSA <- as.Date(cadastrados$DT_PRIMEIRA_DISPENSA, format = "%d/%m/%Y")
cadastrados$DATA_ULTIMA_DISPENSA <- as.Date(cadastrados$DT_ULTIMA_DISPENSA, format = "%d/%m/%Y")
cadastrados$EQUIPE <- as.factor(cadastrados$EQUIPE_PACIENTE)

cadastrados$NOME_PAC <- as.character(cadastrados$NOME_PAC)

toRemove <- c("OLX", " OLX")
for (tR in toRemove) {
  cadastrados$NOME_PAC <- gsub(tR, "", cadastrados$NOME_PAC)
}

cadastrados$NOME_PAC <- trimws(as.character(cadastrados$NOME_PAC), "l")
cadastrados$NOME_PAC <- trimws(as.character(cadastrados$NOME_PAC), "r")
cadastrados$NOME_MAE <- trimws(as.character(cadastrados$NOME_MAE), "l")
cadastrados$NOME_MAE <- trimws(as.character(cadastrados$NOME_MAE), "r")

cadastrados$NOME_MAE[cadastrados$NOME_MAE == ""] <- NA

novo <- cadastrados %>% select(PACIENTE_ID, NOME_PAC, DATA_NASC, NOME_MAE, NOME_UNIDADE, DATA_INSCRICAO,
                               MICRO_AREA, DATA_PRIMEIRO_ATEND, DATA_ULTIMO_ATEND, DATA_PRIMEIRA_VISITA, 
                               DATA_ULTIMA_VISITA, DATA_PRIMEIRA_DISPENSA, DATA_ULTIMA_DISPENSA, EQUIPE)

save(novo, file = "C:\\Users\\Adelson\\Desktop\\pendrive\\bancos_workspace\\novo.RData")

```


# Patients subscribed in each clinic

```{r}
clinicas <- novo %>% group_by(NOME_UNIDADE) %>% count() 

kableExtra::kable(clinicas) %>% kable_styling(bootstrap_options = c("striped", "hover"))

```


# Patients subscribed in each Family Health Team

```{r}
equipes <- novo %>% group_by(NOME_UNIDADE, EQUIPE) %>% count() 

kableExtra::kable(equipes) %>% kable_styling(bootstrap_options = c("striped", "hover"))

```




